site_name: Social Buddy

plugins:
  - search
  - encryptcontent:
        global_password: 'askion'

nav:
 - Home: index.md
 - Buddy Bot: buddy_bot
 - Void: general_notes

theme: 
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences